### ISSUE TITLE
The mod doesn't work at all | 1.16.3

### ISSUE THREAD

**Issue by pr1nce55** [nanite/Simple-Discord-Rich-Presence#11]
I downloaded the mod and copied it to the /mods folder. It is in the list, but nothing happens and I can't open the config
![image](https://user-images.githubusercontent.com/36086205/98152176-573d2800-1ee2-11eb-8b0d-850f23c2afcc.png)

**Comment by Algester** [comment]
from what I'm seeing this is just an API to attach minecraft to discord you need to work it out on discord's end with rich presence integration either have a bot handling the connection or make your own

**Comment by maccree** [comment]
Hmm, maybe I didn't understand how to use the mod correctly. Where can I read the documentation?

**Comment by Algester** [comment]
not sure
maybe this?
https://discord.com/developers/docs/rich-presence/how-to

**Comment by CyberByte-js** [comment]
You are in 1.16.3 and the mod is in 1.16.2 ;-;

**Comment by Sunekaer** [comment]
Do you have it disabled in your discord settings?
