### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by NepNep21** [nanite/Simple-Discord-Rich-Presence#16]
`SimpleDiscordRichPresence-1.16.4-1.3.5.jar`
I am on arch linux with a fairly up to date system (i upgraded everything last week), using the community/discord package, though i don't think this is a discord issue since other apps like intellij and vscodium work fine

Latest log:  https://paste.ee/p/iUpug
Part of the debug log that seems relevant to this: https://paste.ee/p/T3qA8

The above logs are from a clean 1.16.5 instance, but i also get the same messages in enigmatica 6, the mentioned files do exist

**Comment by Sunekaer** [comment]
This is not something i can fix, due to the lib not support your os
