### ISSUE TITLE
[Issue] Frozen on launch

### ISSUE THREAD

**Issue by Darkere** [nanite/Simple-Discord-Rich-Presence#17]
### Mod version

SimpleDiscordRichPresence-1.16.4-1.3.5.jar

### Forge mod loader version

36.2.8

### Repeatable?

- [ ] Yes

### Steps to reproduce the issue

Launch. Presumably this is incredibly rare.

While we do have plenty of complains about long load times I don't recall many reports of infinite ones. 

### Description of the issue you are having

The game is stuck during launch. 
Last message in the latest.log is this: 
``` 
[31Oct2021 17:32:44.220] [Render thread/ERROR] [Simple Discord Rich Presence/]: java.lang.RuntimeException: java.io.IOException: The pipe is being closed
[31Oct2021 17:32:44.394] [Render thread/INFO] [IPCClient/]: Found preferred client: ANY
```

Full debug Log: https://gist.githubusercontent.com/Darkere/d9ccafe088987fa73e5d8e790091306e/raw/b886fe1bbac4fd50708f69a72c6f07d79c844d7b/gistfile1.txt

Visual VM shows this: 
![image](https://user-images.githubusercontent.com/4283717/139594014-7d36f930-62fa-4aa1-9568-566268753226.png)

[Visualvm snapshot](https://github.com/Sunekaer/Simple-Discord-Rich-Presence/files/7449279/sdrp_stuck.zip)

### Information

- [X] I have provided as much information as possible

**Comment by aaronhowser1** [comment]
You put the entire second half of the issue as a code block, so embeds don't work

**Comment by Darkere** [comment]
oops fixed

**Comment by Sunekaer** [comment]
Should be fixed by Michaels update
