### ISSUE TITLE
[Feature Request] How to change logo?

### ISSUE THREAD

**Issue by bynoment** [nanite/Simple-Discord-Rich-Presence#20]
### Feature Description

Hello im new in coding i edited .jar file logo.png and eng.txt 
But logo doesnt changing how i change logo?

And how i rebuild .jar?

**Comment by Sunekaer** [comment]
Why would you need to rebuild the jar?
Also you need to add the img with name logo on the application on Discord dev site

**Comment by bynoment** [comment]
My issue is this
i edited .jar logo.png but its opening srdplogo.png 
https://imgur.com/cPU80ph
https://imgur.com/E5POUmP 
I want to change this logo and texts 
i edited end_us.json but its doesnt changing

I tried and not changing after
And i try to edit and rebuild this jar 
https://imgur.com/b2P3Od3

How i change logo and texts? without rebuilding jar

**Comment by Sunekaer** [comment]
As i said you dont edit the jar...
For logo and other images you have to make an application on https://discord.com/developers and add the image on the Rich Presence Art Assets 
lang file you overwrite with a datapack and not by changing the jar

**Comment by Sunekaer** [comment]
You put you application id in the config file for the mod

**Comment by bynoment** [comment]
I cant find a where i put clientID = application id 
Here is the config file location its true?
\Simple-Discord-Rich-Presence-Mod-1.16.5\com\sunekaer\mods\sdrp\config 
and its .class i cant edit

Can u give a file location + where is i chage for discord application?

**Comment by Sunekaer** [comment]
Again dont touch the JAR file!
go to the config folder for your instance and change the config file for SRDP

**Comment by bynoment** [comment]
Finally i found okay thank you!
