### ISSUE TITLE
Linux compat backport [Feature Request] 

### ISSUE THREAD

**Issue by NoPyro** [nanite/Simple-Discord-Rich-Presence#21]
### Feature Description

for 1.19 this mod was rewritten to support linux, however pre-1.19 versions of the game remain unable to use this mod on linux, would it be possible to backport the 2.0 version to at least 1.18 at all? the only alternative mod is much more difficult to set up and having linux support for this mod would be a huge time saver.

**Comment by Sunekaer** [comment]
Ported to 1.18.2
