### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by BlueFire2003** [nanite/Simple-Discord-Rich-Presence#31]
### Feature Description

1-Custom description for the rpc,instead of showing main menu or overworld or things like this it would be cool to be able to put some modpack description there
2-Buttons for rpc,It would be even better to be able to place a link for the modpack in the rich presence

If u plan to do these in the future,please make them for 1.19.2 too

**Comment by ooliver1** [comment]
> For the message (stuff like "In Overworld") is done via lang keys "sdrp.<registry name path of the dimension>.in"
For imageName (stuff like "Overworld" when hovering over the small image) is done via lang keys "sdrp.<registry name path of the dimension>"

Lang keys can be modified and added via data packs and using mods like KubeJS
