### ISSUE TITLE
How to make localization without KubeJS?

### ISSUE THREAD

**Issue by mikhailfluffy** [nanite/Simple-Discord-Rich-Presence#38]
### Minecraft Version

1.20.1

### Modloader

fabric-0.16.9

### Mod version

fabric-4.0.3-build.40+mc1.20.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

-

### Steps to reproduce the issue

-

### Description of the issue you are having

I rechecked config file and find only a "sdrp-common.json"
I tried to add strings: "sdrp.mainmenu": "В главном меню"
But after restarting game, string removing.
How I can make localization without KubeJS?

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment]
You can add them via a resource pack
